# Hyperparameter optimization for ultraheavy diquark ML-based signal detection

In [117]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [118]:
df = pd.read_parquet("/home/gmajeri/notebooks/data_new_features_6_jets.parquet")

df

,jet_multiplicity,combined_invariant_mass,sphericity,aplanarity,centrality,total_energy,total_transverse_momentum,p_T_min,p_T_mean,p_T_stddev,...,chi2_3_mean,chi2_3_max,2jet_invariant_mass_mean,2jet_invariant_mass_stddev,3jet_invariant_mass_mean,3jet_invariant_mass_stddev,6jet_invariant_mass_mean,6jet_invariant_mass_stddev,n_jet_pairs_near_w_mass,label
index,,,,,,,,,,,,,,,,,,,,,
0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0,BKG:gg_bbbar
0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0,BKG:gg_bbbar
4656569659233790776,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0,BKG:gg_bbbar
0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0,BKG:gg_bbbar
4653989647435531168,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0,BKG:gg_bbbar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,5,7459.883197,0.029608,0.000286,0.560534,7462.769043,4183.134277,60.601192,836.626855,783.006900,...,0.000000,0.000000,1470.769043,1844.404083,3236.501758,2493.996065,0.00000,0.0,1,SIG:Suu
0,6,7475.343691,0.031678,0.002972,0.622338,7484.976562,4658.182129,45.025780,776.363688,836.250963,...,27.526419,27.526419,1150.550130,1549.715758,2503.402734,2215.655467,7475.34375,0.0,0,SIG:Suu
0,5,7067.953118,0.173947,0.059047,0.442356,7367.555176,3259.083008,50.120354,651.816602,375.098078,...,0.000000,0.000000,1808.013477,1314.033207,3596.017188,1433.684340,0.00000,0.0,0,SIG:Suu
0,4,7777.465436,0.297268,0.050678,0.890534,7935.774414,7067.077148,763.408203,1766.769287,770.174679,...,0.000000,0.000000,2957.042318,1156.458126,5408.846191,994.417859,0.00000,0.0,0,SIG:Suu
0,5,7726.890468,0.222409,0.027486,0.701761,7735.790039,5428.678711,47.509563,1085.735742,733.102106,...,0.000000,0.000000,1888.200781,1550.864472,3875.344922,1700.926611,0.00000,0.0,0,SIG:Suu

In [119]:
X = df.drop(columns="label")
y: pd.Series = df["label"] == "SIG:Suu"

In [120]:
num_signal = (y == 1).sum()
bkg_mask = y == 0
X_bkg = X.iloc[bkg_mask].sample(n=num_signal, replace=False, random_state=7)
y_bkg = y.iloc[bkg_mask].sample(n=num_signal, replace=False, random_state=7)

X_sgn = X.iloc[~bkg_mask]
y_sgn = y.iloc[~bkg_mask]

X_balanced = pd.concat((X_bkg, X_sgn), ignore_index=True).reindex()
y_balanced = pd.concat((y_bkg, y_sgn), ignore_index=True).reindex()

In [121]:
from sklearn.model_selection import StratifiedKFold

# from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import average_precision_score

In [122]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=7)

In [123]:
average_precision_scores = np.empty(skf.get_n_splits(), dtype=np.float64)

for i, (train_index, test_index) in enumerate(skf.split(X_balanced, y_balanced)):
    X_train = X_balanced.iloc[train_index]
    y_train = y_balanced.iloc[train_index]
    X_test = X_balanced.iloc[test_index]
    y_test = y_balanced.iloc[test_index]

    print(f"Fold #{i + 1}")
    print(
        f"  We have a total of {(y_train == 0).sum()} backgrounds for training and {(y_test == 0).sum()} for testing"
    )

    train_signals_count = (y_train == 1).sum()
    test_signals_count = (y_test == 1).sum()
    print(
        f"  We're training on {train_signals_count} signals and testing on {test_signals_count} signals"
    )

    # print("  Subsampling backgrounds")

    # bkg_train_mask = y_train == 0

    # X_train_bkg = X_train.iloc[bkg_train_mask].iloc[:train_signals_count]
    # y_train_bkg = y_train.iloc[bkg_train_mask].iloc[:train_signals_count]

    # X_train_sig = X_train.iloc[~bkg_train_mask]
    # y_train_sig = y_train.iloc[~bkg_train_mask]

    # X_train = pd.concat((X_train_bkg, X_train_sig), ignore_index=True)
    # y_train = pd.concat((y_train_bkg, y_train_sig), ignore_index=True)

    # print(f"  Now we're training on {(y_train == 1).sum()} signals and {(y_train == 0).sum()} backgrounds")

    # print("  Fitting logistic regression model...")
    # clf = LogisticRegression(max_iter=1000, random_state=42, l1_ratio=0)
    # clf.fit(X_train, y_train)

    print("  Fitting random forest classifier...")
    clf = RandomForestClassifier(n_jobs=120, random_state=42, verbose=1)
    clf.fit(X_train, y_train)

    y_test_predicted = clf.predict_proba(X_test)
    assert isinstance(y_test_predicted, np.ndarray)

    # First column is probability of being background, second column is probability of being signal
    y_test_predicted = y_test_predicted[:, 1]

    aps = average_precision_score(y_test, y_test_predicted)
    print("Average precision score:", aps)

    average_precision_scores[i] = aps

Fold #1
  We have a total of 74111 backgrounds for training and 18528 for testing
  We're training on 74111 signals and testing on 18528 signals
  Fitting random forest classifier...

[Parallel(n_jobs=120)]: Using backend ThreadingBackend with 120 concurrent workers.
[Parallel(n_jobs=120)]: Done  63 out of 100 | elapsed:    1.1s remaining:    0.7s
[Parallel(n_jobs=120)]: Done 100 out of 100 | elapsed:    1.3s finished
[Parallel(n_jobs=100)]: Using backend ThreadingBackend with 100 concurrent workers.
[Parallel(n_jobs=100)]: Done   2 out of 100 | elapsed:    0.0s remaining:    1.2s
[Parallel(n_jobs=100)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=120)]: Using backend ThreadingBackend with 120 concurrent workers.

Average precision score: 0.9953570358077828
Fold #2
  We have a total of 74111 backgrounds for training and 18528 for testing
  We're training on 74111 signals and testing on 18528 signals
  Fitting random forest classifier...

[Parallel(n_jobs=120)]: Done  63 out of 100 | elapsed:    1.1s remaining:    0.6s
[Parallel(n_jobs=120)]: Done 100 out of 100 | elapsed:    1.4s finished
[Parallel(n_jobs=100)]: Using backend ThreadingBackend with 100 concurrent workers.
[Parallel(n_jobs=100)]: Done   2 out of 100 | elapsed:    0.0s remaining:    1.0s
[Parallel(n_jobs=100)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=120)]: Using backend ThreadingBackend with 120 concurrent workers.

Average precision score: 0.9958098688897338
Fold #3
  We have a total of 74111 backgrounds for training and 18528 for testing
  We're training on 74111 signals and testing on 18528 signals
  Fitting random forest classifier...

[Parallel(n_jobs=120)]: Done  63 out of 100 | elapsed:    1.1s remaining:    0.6s
[Parallel(n_jobs=120)]: Done 100 out of 100 | elapsed:    1.3s finished
[Parallel(n_jobs=100)]: Using backend ThreadingBackend with 100 concurrent workers.
[Parallel(n_jobs=100)]: Done   2 out of 100 | elapsed:    0.0s remaining:    1.2s
[Parallel(n_jobs=100)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=120)]: Using backend ThreadingBackend with 120 concurrent workers.

Average precision score: 0.9953341765556964
Fold #4
  We have a total of 74111 backgrounds for training and 18528 for testing
  We're training on 74112 signals and testing on 18527 signals
  Fitting random forest classifier...

[Parallel(n_jobs=120)]: Done  63 out of 100 | elapsed:    1.1s remaining:    0.7s
[Parallel(n_jobs=120)]: Done 100 out of 100 | elapsed:    1.3s finished
[Parallel(n_jobs=100)]: Using backend ThreadingBackend with 100 concurrent workers.
[Parallel(n_jobs=100)]: Done   2 out of 100 | elapsed:    0.0s remaining:    1.0s
[Parallel(n_jobs=100)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=120)]: Using backend ThreadingBackend with 120 concurrent workers.

Average precision score: 0.9952098594084503
Fold #5
  We have a total of 74112 backgrounds for training and 18527 for testing
  We're training on 74111 signals and testing on 18528 signals
  Fitting random forest classifier...

[Parallel(n_jobs=120)]: Done  63 out of 100 | elapsed:    1.1s remaining:    0.7s

Average precision score: 0.9944458799846088

[Parallel(n_jobs=120)]: Done 100 out of 100 | elapsed:    1.4s finished
[Parallel(n_jobs=100)]: Using backend ThreadingBackend with 100 concurrent workers.
[Parallel(n_jobs=100)]: Done   2 out of 100 | elapsed:    0.0s remaining:    1.0s
[Parallel(n_jobs=100)]: Done 100 out of 100 | elapsed:    0.0s finished

## Baseline performance

In [124]:
print(
    f"Average precision score (overall): mean={average_precision_scores.mean()} std={average_precision_scores.std()}"
)

Average precision score (overall): mean=0.9952313641292545 std=0.0004423752520697547

In [125]:
probs = clf.predict_proba(X)
assert isinstance(probs, np.ndarray)

[Parallel(n_jobs=100)]: Using backend ThreadingBackend with 100 concurrent workers.
[Parallel(n_jobs=100)]: Done   2 out of 100 | elapsed:    0.3s remaining:   13.6s
[Parallel(n_jobs=100)]: Done 100 out of 100 | elapsed:    0.8s finished

In [126]:
np.nonzero(probs[:, 1].round().astype(np.int32).astype(np.float64) != probs[:, 1])

(array([     32,      90,     167, ..., 2992631, 2992634, 2992635],
       shape=(534662,)),)

In [127]:
average_precision_score(y, probs[:, 1])

0.9140763043087048

In [128]:
from diquark.evaluation.metrics import calculate_counts_for_score_cuts

CROSS_SECTION_ATLAS_136_80 = {
    'BKG:gg_bbbar': 6.281E-04,
    'BKG:gg_ccbar': 6.362E-03,
    'BKG:gg_gg': 1.004E+07,
    'BKG:qqbar_gg': 3.639E-01,
    'BKG:gg_qqbar': 5.715E-02,
    'BKG:qg_qg': 3.058E+08,
    'BKG:qqbar_bbbar': 2.016E-05,
    'BKG:qqbar_ccbar': 2.013E-05,
    'BKG:qq_qq': 1.450E+09,
    'BKG:qqbar_qqbarNew': 6.053E-05,
    'BKG:qq_hbb_hadronic': 7.679E-11,
    'BKG:gg_hbb_hadronic': 6.318E-09,
    'BKG:gg_Hg': 4.014E-04,
    'BKG:qg_Hq_loop': 6.973E-03,
    'BKG:qqbar_Hg': 0,
    'BKG:ff_H': 0,
    'BKG:gg_H': 0,
    'BKG:ff_HZ': 1.447E-08,
    'BKG:ff_HW': 1.503E-08,
    'BKG:ff_Hff': 2.316E-02,
    'BKG:ff_Hff2': 3.986E-02,
    'BKG:gg_Httbar': 1.287E-07,
    'BKG:qq_Httbar': 1.448E-07,
    'BKG:qg_Hq': 1.411E-10,
    'BKG:ffbar_Wgm': 2.102E-05,
    'BKG:qg_Wj_hadronic': 9.486E-03,
    'BKG:qqbar_Wj_hadronic': 2.401E-03,
    'BKG:ff_ZW_bkg': 7.209E-06,
    'BKG:ff_WW_bkg': 2.738E-05,
    'BKG:ff_gmZgmZ_bkg': 2.298E-06,
    'BKG:gg_ttbar_bkg_hadronic': 8.018E-06,
    'BKG:qq_ttbar_bkg_hadronic': 9.390E-06,
    # Fixed cross section
    'SIG:Suu': 2.406E-03,
}

df_counts = calculate_counts_for_score_cuts(
    y,
    probs[:, 1],
    X["combined_invariant_mass"],
    df["label"],
    cross_sections=CROSS_SECTION_ATLAS_136_80,
    total_luminosity=3000,
    cuts=[0.0, 0.25, 0.5, 0.6, 0.75, 0.8, 0.9, 1.0],
    use_real_event_percentiles=False,
)

In [129]:
df_counts

,Process,0.0,0.25,0.5,0.6,0.75,0.8,0.9,1.0
0,BKG:ff_HW,1.228026e-05,1.228026e-05,1.228026e-05,1.228026e-05,1.228026e-05,1.228026e-05,3.288865e-06,0.0
1,BKG:ff_HZ,1.212919e-05,1.212919e-05,1.212919e-05,1.212919e-05,1.212919e-05,1.212919e-05,3.367748e-06,0.0
2,BKG:ff_Hff,2.552000e+00,2.552000e+00,2.552000e+00,2.552000e+00,2.552000e+00,2.552000e+00,1.278432e-01,0.0
3,BKG:ff_Hff2,3.657952e+00,3.657952e+00,3.657952e+00,3.657952e+00,3.657952e+00,3.657952e+00,1.602372e-01,0.0
4,BKG:ff_WW_bkg,2.736823e-02,2.736823e-02,2.736823e-02,2.736823e-02,2.736823e-02,2.736823e-02,1.841661e-02,0.0
5,BKG:ff_ZW_bkg,1.458741e-03,1.458741e-03,1.458741e-03,1.458741e-03,1.458741e-03,1.458741e-03,3.200796e-04,0.0
6,BKG:ff_gmZgmZ_bkg,9.583349e-04,9.583349e-04,9.583349e-04,9.583349e-04,9.583349e-04,9.583349e-04,4.216370e-04,0.0
7,BKG:ffbar_Wgm,4.470323e-03,4.470323e-03,4.470323e-03,4.470323e-03,4.470323e-03,4.470323e-03,1.906934e-03,0.0
8,BKG:gg_Hg,3.997944e-03,3.997944e-03,3.997944e-03,3.997944e-03,3.997944e-03,3.997944e-03,7.345620e-04,0.0
9,BKG:gg_Httbar,2.453859e-04,2.453859e-04,2.453859e-04,2.453859e-04,2.453859e-04,2.453859e-04,1.174593e-04,0.0
10,BKG:gg_bbbar,1.552663e-02,1.552663e-02,1.552663e-02,1.552663e-02,1.552663e-02,1.552663e-02,2.411904e-03,0.0
11,BKG:gg_ccbar,1.584138e-02,1.584138e-02,1.584138e-02,1.584138e-02,1.584138e-02,1.584138e-02,2.099460e-03,0.0
12,BKG:gg_gg,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
13,BKG:gg_hbb_hadronic,1.124730e-06,1.124730e-06,1.124730e-06,1.124730e-06,1.124730e-06,1.124730e-06,2.765389e-07,0.0
14,BKG:gg_qqbar,3.257550e-02,3.257550e-02,3.257550e-02,3.257550e-02,3.257550e-02,3.257550e-02,1.714500e-03,0.0
15,BKG:gg_ttbar_bkg_hadronic,6.522242e-03,6.522242e-03,6.522242e-03,6.522242e-03,6.522242e-03,6.522242e-03,9.431573e-04,0.0
16,BKG:qg_Hq,2.963947e-08,2.963947e-08,2.963947e-08,2.963947e-08,2.963947e-08,2.963947e-08,4.482747e-09,0.0
17,BKG:qg_Hq_loop,8.869656e-02,8.869656e-02,8.869656e-02,8.869656e-02,8.869656e-02,8.869656e-02,1.045950e-02,0.0
18,BKG:qg_Wj_hadronic,4.598813e-01,4.598813e-01,4.598813e-01,4.598813e-01,4.598813e-01,4.598813e-01,1.274918e-01,0.0
19,BKG:qg_qg,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
20,BKG:qq_Httbar,3.257522e-04,3.257522e-04,3.257522e-04,3.257522e-04,3.257522e-04,3.257522e-04,1.868137e-04,0.0
21,BKG:qq_hbb_hadronic,1.794467e-07,1.794467e-07,1.794467e-07,1.794467e-07,1.794467e-07,1.794467e-07,1.078846e-07,0.0
22,BKG:qq_qq,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
23,BKG:qq_ttbar_bkg_hadronic,8.785378e-03,8.785378e-03,8.785378e-03,8.785378e-03,8.785378e-03,8.785378e-03,2.043170e-03,0.0
24,BKG:qqbar_Wj_hadronic,3.455279e-01,3.455279e-01,3.455279e-01,3.455279e-01,3.455279e-01,3.455279e-01,1.592583e-01,0.0
25,BKG:qqbar_bbbar,2.055836e-02,2.055836e-02,2.055836e-02,2.055836e-02,2.055836e-02,2.055836e-02,5.444410e-03,0.0
26,BKG:qqbar_ccbar,1.746358e-02,1.746358e-02,1.746358e-02,1.746358e-02,1.746358e-02,1.746358e-02,3.919311e-03,0.0
27,BKG:qqbar_gg,1.320957e+00,1.320957e+00,1.320957e+00,1.320957e+00,1.320957e+00,1.320957e+00,4.585140e-01,0.0
28,BKG:qqbar_qqbarNew,4.317847e-02,4.317847e-02,4.317847e-02,4.317847e-02,4.317847e-02,4.317847e-02,7.530537e-03,0.0
29,SIG:Suu,7.217844e+00,7.217844e+00,7.217844e+00,7.217844e+00,7.217844e+00,7.217844e+00,7.215896e+00,0.0
30,BKG:sum,8.624317e+00,8.624317e+00,8.624317e+00,8.624317e+00,8.624317e+00,8.624317e+00,1.092022e+00,0.0
31,S/B,8.369177e-01,8.369177e-01,8.369177e-01,8.369177e-01,8.369177e-01,8.369177e-01,6.607833e+00,NaN

In [130]:
from sklearn.model_selection import GridSearchCV

In [131]:
param_grid = [
    {"criterion": ["gini"], "n_estimators": [10, 50, 100, 200, 300, 400]},
    {"criterion": ["entropy"], "n_estimators": [10, 50, 100, 200, 300, 400]},
]

clf = RandomForestClassifier(n_jobs=-1, verbose=0)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=i)

print("Doing nested cross-validation with hyperparameter optimization")

# Grid search CV with parameter optimization
gsc = GridSearchCV(estimator=clf, param_grid=param_grid, cv=skf, verbose=2)
gsc.fit(X_balanced, y_balanced)
cv_results = gsc.cv_results_

Doing nested cross-validation with hyperparameter optimization
Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END ....................criterion=gini, n_estimators=10; total time=   1.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   1.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   1.0s
[CV] END ....................criterion=gini, n_estimators=10; total time=   1.1s
[CV] END ....................criterion=gini, n_estimators=10; total time=   0.9s
[CV] END ....................criterion=gini, n_estimators=50; total time=   1.2s
[CV] END ....................criterion=gini, n_estimators=50; total time=   1.3s
[CV] END ....................criterion=gini, n_estimators=50; total time=   1.2s
[CV] END ....................criterion=gini, n_estimators=50; total time=   1.2s
[CV] END ....................criterion=gini, n_estimators=50; total time=   1.3s
[CV] END ...................criterion=gini, n_estimators=100; total time=   1.5s
[CV] END ...................criterion=gini, n_estimators=100; total time=   1.5s
[CV] END ...................criterion=gini, n_estimators=100; total time=   1.4s
[CV] END ...................criterion=gini, n_estimators=100; total time=   1.5s
[CV] END ...................criterion=gini, n_estimators=100; total time=   1.4s
[CV] END ...................criterion=gini, n_estimators=200; total time=   2.3s
[CV] END ...................criterion=gini, n_estimators=200; total time=   2.4s
[CV] END ...................criterion=gini, n_estimators=200; total time=   2.4s
[CV] END ...................criterion=gini, n_estimators=200; total time=   2.4s
[CV] END ...................criterion=gini, n_estimators=200; total time=   2.4s
[CV] END ...................criterion=gini, n_estimators=300; total time=   3.4s
[CV] END ...................criterion=gini, n_estimators=300; total time=   3.2s
[CV] END ...................criterion=gini, n_estimators=300; total time=   3.2s
[CV] END ...................criterion=gini, n_estimators=300; total time=   3.2s
[CV] END ...................criterion=gini, n_estimators=300; total time=   3.4s
[CV] END ...................criterion=gini, n_estimators=400; total time=   3.9s
[CV] END ...................criterion=gini, n_estimators=400; total time=   4.0s
[CV] END ...................criterion=gini, n_estimators=400; total time=   4.0s
[CV] END ...................criterion=gini, n_estimators=400; total time=   4.0s
[CV] END ...................criterion=gini, n_estimators=400; total time=   3.9s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.8s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.8s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.8s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.8s
[CV] END .................criterion=entropy, n_estimators=10; total time=   0.7s
[CV] END .................criterion=entropy, n_estimators=50; total time=   1.0s
[CV] END .................criterion=entropy, n_estimators=50; total time=   1.1s
[CV] END .................criterion=entropy, n_estimators=50; total time=   1.2s
[CV] END .................criterion=entropy, n_estimators=50; total time=   1.1s
[CV] END .................criterion=entropy, n_estimators=50; total time=   1.0s
[CV] END ................criterion=entropy, n_estimators=100; total time=   1.2s
[CV] END ................criterion=entropy, n_estimators=100; total time=   1.4s
[CV] END ................criterion=entropy, n_estimators=100; total time=   1.4s
[CV] END ................criterion=entropy, n_estimators=100; total time=   1.3s
[CV] END ................criterion=entropy, n_estimators=100; total time=   1.3s
[CV] END ................criterion=entropy, n_estimators=200; total time=   2.1s
[CV] END ................criterion=entropy, n_estimators=200; total time=   2.0s
[CV] END ................criterion=entropy, n_estimators=200; total time=   2.0s
[CV] END ................criterion=entropy, n_estimators=200; total time=   2.0s
[CV] END ................criterion=entropy, n_estimators=200; total time=   2.1s
[CV] END ................criterion=entropy, n_estimators=300; total time=   2.8s
[CV] END ................criterion=entropy, n_estimators=300; total time=   2.9s
[CV] END ................criterion=entropy, n_estimators=300; total time=   2.7s
[CV] END ................criterion=entropy, n_estimators=300; total time=   2.8s
[CV] END ................criterion=entropy, n_estimators=300; total time=   2.7s
[CV] END ................criterion=entropy, n_estimators=400; total time=   3.3s
[CV] END ................criterion=entropy, n_estimators=400; total time=   3.4s
[CV] END ................criterion=entropy, n_estimators=400; total time=   3.5s
[CV] END ................criterion=entropy, n_estimators=400; total time=   3.5s
[CV] END ................criterion=entropy, n_estimators=400; total time=   3.3s

In [132]:
cv_results

{'mean_fit_time': array([0.98844929, 1.19044838, 1.39229851, 2.30638714, 3.1594615 ,
        3.87391138, 0.78256779, 1.05905285, 1.27608218, 1.96724882,
        2.64489055, 3.30145097]),
 'std_fit_time': array([0.07150899, 0.03372254, 0.04949111, 0.03925637, 0.05457396,
        0.06101224, 0.041127  , 0.04638046, 0.07955688, 0.0249355 ,
        0.05230263, 0.07659923]),
 'mean_score_time': array([0.01912231, 0.03483205, 0.05799131, 0.07738929, 0.12727304,
        0.10425973, 0.01712503, 0.03238111, 0.05442309, 0.06994071,
        0.12041683, 0.10376787]),
 'std_score_time': array([0.00194135, 0.0018219 , 0.00192156, 0.00613439, 0.06712492,
        0.00656053, 0.00101854, 0.00104032, 0.00239102, 0.00220869,
        0.06051106, 0.00681593]),
 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_estimators': masked_array(data=[10, 50, 100, 200, 300, 400, 10, 50, 100, 200, 300, 400],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'params': [{'criterion': 'gini', 'n_estimators': 10},
  {'criterion': 'gini', 'n_estimators': 50},
  {'criterion': 'gini', 'n_estimators': 100},
  {'criterion': 'gini', 'n_estimators': 200},
  {'criterion': 'gini', 'n_estimators': 300},
  {'criterion': 'gini', 'n_estimators': 400},
  {'criterion': 'entropy', 'n_estimators': 10},
  {'criterion': 'entropy', 'n_estimators': 50},
  {'criterion': 'entropy', 'n_estimators': 100},
  {'criterion': 'entropy', 'n_estimators': 200},
  {'criterion': 'entropy', 'n_estimators': 300},
  {'criterion': 'entropy', 'n_estimators': 400}],
 'split0_test_score': array([0.97428217, 0.97719668, 0.97681887, 0.97700777, 0.9769538 ,
        0.97722366, 0.97533463, 0.97698079, 0.97738558, 0.97722366,
        0.97741256, 0.97730462]),
 'split1_test_score': array([0.97611723, 0.97770941, 0.97803325, 0.9779253 , 0.9779253 ,
        0.97787133, 0.97503778, 0.9775475 , 0.97806023, 0.97789832,
        0.97827612, 0.97824914]),
 'split2_test_score': array([0.97725065, 0.97857297, 0.97886982, 0.97884283, 0.97919365,
        0.97884283, 0.97646805, 0.97841105, 0.97876187, 0.97892379,
        0.97862694, 0.97911269]),
 'split3_test_score': array([0.97681824, 0.97822156, 0.97851842, 0.97851842, 0.97857239,
        0.97878829, 0.97698016, 0.97827554, 0.97832951, 0.97846444,
        0.97859938, 0.9783565 ]),
 'split4_test_score': array([0.97590069, 0.97795169, 0.9771151 , 0.9781406 , 0.97754689,
        0.97819458, 0.97549588, 0.97708811, 0.97762785, 0.97803265,
        0.97803265, 0.97797868]),
 'mean_test_score': array([0.97607379, 0.97793046, 0.97787109, 0.97808699, 0.97803841,
        0.97818414, 0.9758633 , 0.9776606 , 0.97803301, 0.97810857,
        0.97818953, 0.97820033]),
 'std_test_score': array([0.00101794, 0.0004659 , 0.00079012, 0.00062469, 0.00078109,
        0.00060322, 0.00073608, 0.00059059, 0.00049055, 0.00056996,
        0.00044611, 0.00058491]),
 'rank_test_score': array([11,  8,  9,  5,  6,  3, 12, 10,  7,  4,  2,  1], dtype=int32)}